/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvAccordion {
        "accordionlabels": string;
        /**
          * @default 'div'
         */
        "accordiontype": 'div' | 'section' | 'article';
        "classmodifier"?: string;
        /**
          * @default 'horizontal'
         */
        "layout": 'vertical' | 'horizontal';
        /**
          * @default false
         */
        "showfirst": boolean;
        /**
          * @default false
         */
        "showmultiple": boolean;
        /**
          * @default 0
         */
        "startingpanel": number;
    }
    interface IvBanner {
        "bannerbuttontext"?: string;
        /**
          * @default 'div'
         */
        "bannertype": 'div' | 'section' | 'article';
        "bannerurl"?: string;
        "classmodifier"?: string;
    }
    interface IvButton {
        "buttonClick"?: (e?: MouseEvent) => void;
        "classmodifier"?: string;
        "eventdetail"?: string;
        "eventname"?: string;
        /**
          * @default 'button'
         */
        "type": string;
    }
    interface IvCard {
        "addtocarttext"?: string;
        "buttontext"?: string;
        /**
          * @default false
         */
        "calltoaction": boolean;
        "cardtype"?: string;
        "classmodifier"?: string;
        "data": Record<string, any>;
        "fields"?: string;
    }
    interface IvCarousel {
    }
    interface IvDynamicProducts {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction": boolean;
        /**
          * @default false
         */
        "carousel": boolean;
        /**
          * @default 'all'
         */
        "collectionhandle": string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring": string;
        "gridlayout"?: string;
        /**
          * @default 8
         */
        "limit": number;
        "requestedfields": string;
        /**
          * @default false
         */
        "reversed": boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED'
         */
        "type": 'CREATED' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvDynamicProductsCarousel {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction": boolean;
        /**
          * @default 'all'
         */
        "collectionhandle": string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring": string;
        /**
          * @default 24
         */
        "limit": number;
        "requestedfields": string;
        /**
          * @default false
         */
        "reversed": boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED'
         */
        "type": 'CREATED' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvFilters {
    }
    interface IvLayout {
        "classModifier"?: string;
        /**
          * @default '2rem'
         */
        "gap": string;
        "gridTemplateAreas"?: string;
        /**
          * @default 'center'
         */
        "horizontalAlign": string;
        "sectionId"?: string;
        /**
          * @default 'center'
         */
        "verticalAlign": string;
        /**
          * @default 'div'
         */
        "wrapperTag": string;
    }
    interface IvLink {
        "classmodifier"?: string;
        "linkariaLabel"?: string;
        "linkhref"?: string;
        /**
          * @default 'noopener noreferrer'
         */
        "linkrel": string;
        /**
          * @default '_self'
         */
        "linktarget": '_self' | '_blank' | '_parent' | '_top';
        /**
          * @default 'inline'
         */
        "linktype": 'inline' | 'wrapper' | 'nav' | 'button';
    }
    interface IvModal {
    }
    interface IvPredictiveSearch {
        "action"?: string;
        "clearbutton"?: string;
        /**
          * @default 300
         */
        "debounce": number;
        /**
          * @default false
         */
        "expandable": boolean;
        "gridlayout"?: string;
        /**
          * @default 'top'
         */
        "labelposition"?: 'inline' | 'top';
        /**
          * @default 'get'
         */
        "method": 'get' | 'post';
        /**
          * @default 3
         */
        "minchars": number;
        /**
          * @default 'No results found'
         */
        "noresultstext": string;
        "placeholder"?: string;
        "querybuttontext"?: string;
        /**
          * @default 'title'
         */
        "requestedfields": string;
        /**
          * @default 'product,article,page,collection'
         */
        "requestedresources": string;
        /**
          * @default 5
         */
        "resultslimit": number;
        "searchlabel"?: string;
        "showallbuttontext"?: string;
        "showspinner"?: boolean;
        "tablayout"?: string;
    }
    interface IvRecentlyViewed {
        "componenttitle"?: string;
        "noviewhistory"?: string;
        /**
          * @default 4
         */
        "numbertoshow": number;
        /**
          * @default 'images,title,price'
         */
        "requestedfields"?: string;
        /**
          * @default 'span'
         */
        "titletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
    }
    interface IvSidebar {
        /**
          * @default '×'
         */
        "closeicon": string;
    }
    interface IvSpinner {
        /**
          * @default false
         */
        "show": boolean;
    }
    interface IvSuggest {
        "banner"?: string;
        "bannerbuttontext"?: string;
        "bannertitle"?: string;
        /**
          * @default 'span'
         */
        "bannertitletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        "bannerurl"?: string;
        "collections"?: string;
        "collectionstitle"?: string;
        "gridlayout"?: string;
        "products"?: string;
        "productstitle"?: string;
        "requestfields"?: string;
        "topqueries"?: string;
        "topquerytitle"?: string;
    }
    interface IvTabs {
        "classModifier"?: string;
        /**
          * @default []
         */
        "labels": string[];
        /**
          * @default 'horizontal'
         */
        "tabLayout": 'horizontal' | 'vertical';
    }
    interface IvToast {
        /**
          * @default 3000
         */
        "duration": number;
        "message": string;
        "toastId": number;
        /**
          * @default 'info'
         */
        "type": 'info' | 'success' | 'error' | 'warning';
    }
    interface IvToastContainer {
    }
    interface IvWishlist {
        /**
          * @default 'Add to cart'
         */
        "buttonaddtocartvalue": string;
        /**
          * @default 'Add to wishlist'
         */
        "buttonaddvalue": string;
        /**
          * @default 'Remove from wishlist'
         */
        "buttonremovevalue": string;
        /**
          * @default 'modal'
         */
        "previewtype": 'modal' | 'pullout';
        /**
          * @default {}
         */
        "productdata": Record<string, any> | string;
        /**
          * @default 'id,title,price,image,url'
         */
        "usefields": string;
        /**
          * @default 'View wishlist'
         */
        "viewwishlistvalue": string;
        /**
          * @default 'Your wishlist is empty'
         */
        "wishlistempty": string;
    }
    interface IvWishlistView {
    }
    interface SwInGridContent {
    }
    interface SwSizeGuide {
    }
}
export interface IvButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvButtonElement;
}
export interface IvPredictiveSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvPredictiveSearchElement;
}
declare global {
    interface HTMLIvAccordionElement extends Components.IvAccordion, HTMLStencilElement {
    }
    var HTMLIvAccordionElement: {
        prototype: HTMLIvAccordionElement;
        new (): HTMLIvAccordionElement;
    };
    interface HTMLIvBannerElement extends Components.IvBanner, HTMLStencilElement {
    }
    var HTMLIvBannerElement: {
        prototype: HTMLIvBannerElement;
        new (): HTMLIvBannerElement;
    };
    interface HTMLIvButtonElementEventMap {
        "action": any;
    }
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvButtonElementEventMap>(type: K, listener: (this: HTMLIvButtonElement, ev: IvButtonCustomEvent<HTMLIvButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvButtonElementEventMap>(type: K, listener: (this: HTMLIvButtonElement, ev: IvButtonCustomEvent<HTMLIvButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLIvCardElement extends Components.IvCard, HTMLStencilElement {
    }
    var HTMLIvCardElement: {
        prototype: HTMLIvCardElement;
        new (): HTMLIvCardElement;
    };
    interface HTMLIvCarouselElement extends Components.IvCarousel, HTMLStencilElement {
    }
    var HTMLIvCarouselElement: {
        prototype: HTMLIvCarouselElement;
        new (): HTMLIvCarouselElement;
    };
    interface HTMLIvDynamicProductsElement extends Components.IvDynamicProducts, HTMLStencilElement {
    }
    var HTMLIvDynamicProductsElement: {
        prototype: HTMLIvDynamicProductsElement;
        new (): HTMLIvDynamicProductsElement;
    };
    interface HTMLIvDynamicProductsCarouselElement extends Components.IvDynamicProductsCarousel, HTMLStencilElement {
    }
    var HTMLIvDynamicProductsCarouselElement: {
        prototype: HTMLIvDynamicProductsCarouselElement;
        new (): HTMLIvDynamicProductsCarouselElement;
    };
    interface HTMLIvFiltersElement extends Components.IvFilters, HTMLStencilElement {
    }
    var HTMLIvFiltersElement: {
        prototype: HTMLIvFiltersElement;
        new (): HTMLIvFiltersElement;
    };
    interface HTMLIvLayoutElement extends Components.IvLayout, HTMLStencilElement {
    }
    var HTMLIvLayoutElement: {
        prototype: HTMLIvLayoutElement;
        new (): HTMLIvLayoutElement;
    };
    interface HTMLIvLinkElement extends Components.IvLink, HTMLStencilElement {
    }
    var HTMLIvLinkElement: {
        prototype: HTMLIvLinkElement;
        new (): HTMLIvLinkElement;
    };
    interface HTMLIvModalElement extends Components.IvModal, HTMLStencilElement {
    }
    var HTMLIvModalElement: {
        prototype: HTMLIvModalElement;
        new (): HTMLIvModalElement;
    };
    interface HTMLIvPredictiveSearchElementEventMap {
        "searchTermsChanged": any;
    }
    interface HTMLIvPredictiveSearchElement extends Components.IvPredictiveSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvPredictiveSearchElementEventMap>(type: K, listener: (this: HTMLIvPredictiveSearchElement, ev: IvPredictiveSearchCustomEvent<HTMLIvPredictiveSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvPredictiveSearchElementEventMap>(type: K, listener: (this: HTMLIvPredictiveSearchElement, ev: IvPredictiveSearchCustomEvent<HTMLIvPredictiveSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvPredictiveSearchElement: {
        prototype: HTMLIvPredictiveSearchElement;
        new (): HTMLIvPredictiveSearchElement;
    };
    interface HTMLIvRecentlyViewedElement extends Components.IvRecentlyViewed, HTMLStencilElement {
    }
    var HTMLIvRecentlyViewedElement: {
        prototype: HTMLIvRecentlyViewedElement;
        new (): HTMLIvRecentlyViewedElement;
    };
    interface HTMLIvSidebarElement extends Components.IvSidebar, HTMLStencilElement {
    }
    var HTMLIvSidebarElement: {
        prototype: HTMLIvSidebarElement;
        new (): HTMLIvSidebarElement;
    };
    interface HTMLIvSpinnerElement extends Components.IvSpinner, HTMLStencilElement {
    }
    var HTMLIvSpinnerElement: {
        prototype: HTMLIvSpinnerElement;
        new (): HTMLIvSpinnerElement;
    };
    interface HTMLIvSuggestElement extends Components.IvSuggest, HTMLStencilElement {
    }
    var HTMLIvSuggestElement: {
        prototype: HTMLIvSuggestElement;
        new (): HTMLIvSuggestElement;
    };
    interface HTMLIvTabsElement extends Components.IvTabs, HTMLStencilElement {
    }
    var HTMLIvTabsElement: {
        prototype: HTMLIvTabsElement;
        new (): HTMLIvTabsElement;
    };
    interface HTMLIvToastElement extends Components.IvToast, HTMLStencilElement {
    }
    var HTMLIvToastElement: {
        prototype: HTMLIvToastElement;
        new (): HTMLIvToastElement;
    };
    interface HTMLIvToastContainerElement extends Components.IvToastContainer, HTMLStencilElement {
    }
    var HTMLIvToastContainerElement: {
        prototype: HTMLIvToastContainerElement;
        new (): HTMLIvToastContainerElement;
    };
    interface HTMLIvWishlistElement extends Components.IvWishlist, HTMLStencilElement {
    }
    var HTMLIvWishlistElement: {
        prototype: HTMLIvWishlistElement;
        new (): HTMLIvWishlistElement;
    };
    interface HTMLIvWishlistViewElement extends Components.IvWishlistView, HTMLStencilElement {
    }
    var HTMLIvWishlistViewElement: {
        prototype: HTMLIvWishlistViewElement;
        new (): HTMLIvWishlistViewElement;
    };
    interface HTMLSwInGridContentElement extends Components.SwInGridContent, HTMLStencilElement {
    }
    var HTMLSwInGridContentElement: {
        prototype: HTMLSwInGridContentElement;
        new (): HTMLSwInGridContentElement;
    };
    interface HTMLSwSizeGuideElement extends Components.SwSizeGuide, HTMLStencilElement {
    }
    var HTMLSwSizeGuideElement: {
        prototype: HTMLSwSizeGuideElement;
        new (): HTMLSwSizeGuideElement;
    };
    interface HTMLElementTagNameMap {
        "iv-accordion": HTMLIvAccordionElement;
        "iv-banner": HTMLIvBannerElement;
        "iv-button": HTMLIvButtonElement;
        "iv-card": HTMLIvCardElement;
        "iv-carousel": HTMLIvCarouselElement;
        "iv-dynamic-products": HTMLIvDynamicProductsElement;
        "iv-dynamic-products-carousel": HTMLIvDynamicProductsCarouselElement;
        "iv-filters": HTMLIvFiltersElement;
        "iv-layout": HTMLIvLayoutElement;
        "iv-link": HTMLIvLinkElement;
        "iv-modal": HTMLIvModalElement;
        "iv-predictive-search": HTMLIvPredictiveSearchElement;
        "iv-recently-viewed": HTMLIvRecentlyViewedElement;
        "iv-sidebar": HTMLIvSidebarElement;
        "iv-spinner": HTMLIvSpinnerElement;
        "iv-suggest": HTMLIvSuggestElement;
        "iv-tabs": HTMLIvTabsElement;
        "iv-toast": HTMLIvToastElement;
        "iv-toast-container": HTMLIvToastContainerElement;
        "iv-wishlist": HTMLIvWishlistElement;
        "iv-wishlist-view": HTMLIvWishlistViewElement;
        "sw-in-grid-content": HTMLSwInGridContentElement;
        "sw-size-guide": HTMLSwSizeGuideElement;
    }
}
declare namespace LocalJSX {
    interface IvAccordion {
        "accordionlabels"?: string;
        /**
          * @default 'div'
         */
        "accordiontype"?: 'div' | 'section' | 'article';
        "classmodifier"?: string;
        /**
          * @default 'horizontal'
         */
        "layout"?: 'vertical' | 'horizontal';
        /**
          * @default false
         */
        "showfirst"?: boolean;
        /**
          * @default false
         */
        "showmultiple"?: boolean;
        /**
          * @default 0
         */
        "startingpanel"?: number;
    }
    interface IvBanner {
        "bannerbuttontext"?: string;
        /**
          * @default 'div'
         */
        "bannertype"?: 'div' | 'section' | 'article';
        "bannerurl"?: string;
        "classmodifier"?: string;
    }
    interface IvButton {
        "buttonClick"?: (e?: MouseEvent) => void;
        "classmodifier"?: string;
        "eventdetail"?: string;
        "eventname"?: string;
        "onAction"?: (event: IvButtonCustomEvent<any>) => void;
        /**
          * @default 'button'
         */
        "type"?: string;
    }
    interface IvCard {
        "addtocarttext"?: string;
        "buttontext"?: string;
        /**
          * @default false
         */
        "calltoaction"?: boolean;
        "cardtype"?: string;
        "classmodifier"?: string;
        "data"?: Record<string, any>;
        "fields"?: string;
    }
    interface IvCarousel {
    }
    interface IvDynamicProducts {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction"?: boolean;
        /**
          * @default false
         */
        "carousel"?: boolean;
        /**
          * @default 'all'
         */
        "collectionhandle"?: string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring"?: string;
        "gridlayout"?: string;
        /**
          * @default 8
         */
        "limit"?: number;
        "requestedfields"?: string;
        /**
          * @default false
         */
        "reversed"?: boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED'
         */
        "type"?: 'CREATED' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvDynamicProductsCarousel {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction"?: boolean;
        /**
          * @default 'all'
         */
        "collectionhandle"?: string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring"?: string;
        /**
          * @default 24
         */
        "limit"?: number;
        "requestedfields"?: string;
        /**
          * @default false
         */
        "reversed"?: boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED'
         */
        "type"?: 'CREATED' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvFilters {
    }
    interface IvLayout {
        "classModifier"?: string;
        /**
          * @default '2rem'
         */
        "gap"?: string;
        "gridTemplateAreas"?: string;
        /**
          * @default 'center'
         */
        "horizontalAlign"?: string;
        "sectionId"?: string;
        /**
          * @default 'center'
         */
        "verticalAlign"?: string;
        /**
          * @default 'div'
         */
        "wrapperTag"?: string;
    }
    interface IvLink {
        "classmodifier"?: string;
        "linkariaLabel"?: string;
        "linkhref"?: string;
        /**
          * @default 'noopener noreferrer'
         */
        "linkrel"?: string;
        /**
          * @default '_self'
         */
        "linktarget"?: '_self' | '_blank' | '_parent' | '_top';
        /**
          * @default 'inline'
         */
        "linktype"?: 'inline' | 'wrapper' | 'nav' | 'button';
    }
    interface IvModal {
    }
    interface IvPredictiveSearch {
        "action"?: string;
        "clearbutton"?: string;
        /**
          * @default 300
         */
        "debounce"?: number;
        /**
          * @default false
         */
        "expandable"?: boolean;
        "gridlayout"?: string;
        /**
          * @default 'top'
         */
        "labelposition"?: 'inline' | 'top';
        /**
          * @default 'get'
         */
        "method"?: 'get' | 'post';
        /**
          * @default 3
         */
        "minchars"?: number;
        /**
          * @default 'No results found'
         */
        "noresultstext"?: string;
        "onSearchTermsChanged"?: (event: IvPredictiveSearchCustomEvent<any>) => void;
        "placeholder"?: string;
        "querybuttontext"?: string;
        /**
          * @default 'title'
         */
        "requestedfields"?: string;
        /**
          * @default 'product,article,page,collection'
         */
        "requestedresources"?: string;
        /**
          * @default 5
         */
        "resultslimit"?: number;
        "searchlabel"?: string;
        "showallbuttontext"?: string;
        "showspinner"?: boolean;
        "tablayout"?: string;
    }
    interface IvRecentlyViewed {
        "componenttitle"?: string;
        "noviewhistory"?: string;
        /**
          * @default 4
         */
        "numbertoshow"?: number;
        /**
          * @default 'images,title,price'
         */
        "requestedfields"?: string;
        /**
          * @default 'span'
         */
        "titletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
    }
    interface IvSidebar {
        /**
          * @default '×'
         */
        "closeicon"?: string;
    }
    interface IvSpinner {
        /**
          * @default false
         */
        "show"?: boolean;
    }
    interface IvSuggest {
        "banner"?: string;
        "bannerbuttontext"?: string;
        "bannertitle"?: string;
        /**
          * @default 'span'
         */
        "bannertitletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        "bannerurl"?: string;
        "collections"?: string;
        "collectionstitle"?: string;
        "gridlayout"?: string;
        "products"?: string;
        "productstitle"?: string;
        "requestfields"?: string;
        "topqueries"?: string;
        "topquerytitle"?: string;
    }
    interface IvTabs {
        "classModifier"?: string;
        /**
          * @default []
         */
        "labels"?: string[];
        /**
          * @default 'horizontal'
         */
        "tabLayout"?: 'horizontal' | 'vertical';
    }
    interface IvToast {
        /**
          * @default 3000
         */
        "duration"?: number;
        "message"?: string;
        "toastId"?: number;
        /**
          * @default 'info'
         */
        "type"?: 'info' | 'success' | 'error' | 'warning';
    }
    interface IvToastContainer {
    }
    interface IvWishlist {
        /**
          * @default 'Add to cart'
         */
        "buttonaddtocartvalue"?: string;
        /**
          * @default 'Add to wishlist'
         */
        "buttonaddvalue"?: string;
        /**
          * @default 'Remove from wishlist'
         */
        "buttonremovevalue"?: string;
        /**
          * @default 'modal'
         */
        "previewtype"?: 'modal' | 'pullout';
        /**
          * @default {}
         */
        "productdata"?: Record<string, any> | string;
        /**
          * @default 'id,title,price,image,url'
         */
        "usefields"?: string;
        /**
          * @default 'View wishlist'
         */
        "viewwishlistvalue"?: string;
        /**
          * @default 'Your wishlist is empty'
         */
        "wishlistempty"?: string;
    }
    interface IvWishlistView {
    }
    interface SwInGridContent {
    }
    interface SwSizeGuide {
    }
    interface IntrinsicElements {
        "iv-accordion": IvAccordion;
        "iv-banner": IvBanner;
        "iv-button": IvButton;
        "iv-card": IvCard;
        "iv-carousel": IvCarousel;
        "iv-dynamic-products": IvDynamicProducts;
        "iv-dynamic-products-carousel": IvDynamicProductsCarousel;
        "iv-filters": IvFilters;
        "iv-layout": IvLayout;
        "iv-link": IvLink;
        "iv-modal": IvModal;
        "iv-predictive-search": IvPredictiveSearch;
        "iv-recently-viewed": IvRecentlyViewed;
        "iv-sidebar": IvSidebar;
        "iv-spinner": IvSpinner;
        "iv-suggest": IvSuggest;
        "iv-tabs": IvTabs;
        "iv-toast": IvToast;
        "iv-toast-container": IvToastContainer;
        "iv-wishlist": IvWishlist;
        "iv-wishlist-view": IvWishlistView;
        "sw-in-grid-content": SwInGridContent;
        "sw-size-guide": SwSizeGuide;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-accordion": LocalJSX.IvAccordion & JSXBase.HTMLAttributes<HTMLIvAccordionElement>;
            "iv-banner": LocalJSX.IvBanner & JSXBase.HTMLAttributes<HTMLIvBannerElement>;
            "iv-button": LocalJSX.IvButton & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
            "iv-card": LocalJSX.IvCard & JSXBase.HTMLAttributes<HTMLIvCardElement>;
            "iv-carousel": LocalJSX.IvCarousel & JSXBase.HTMLAttributes<HTMLIvCarouselElement>;
            "iv-dynamic-products": LocalJSX.IvDynamicProducts & JSXBase.HTMLAttributes<HTMLIvDynamicProductsElement>;
            "iv-dynamic-products-carousel": LocalJSX.IvDynamicProductsCarousel & JSXBase.HTMLAttributes<HTMLIvDynamicProductsCarouselElement>;
            "iv-filters": LocalJSX.IvFilters & JSXBase.HTMLAttributes<HTMLIvFiltersElement>;
            "iv-layout": LocalJSX.IvLayout & JSXBase.HTMLAttributes<HTMLIvLayoutElement>;
            "iv-link": LocalJSX.IvLink & JSXBase.HTMLAttributes<HTMLIvLinkElement>;
            "iv-modal": LocalJSX.IvModal & JSXBase.HTMLAttributes<HTMLIvModalElement>;
            "iv-predictive-search": LocalJSX.IvPredictiveSearch & JSXBase.HTMLAttributes<HTMLIvPredictiveSearchElement>;
            "iv-recently-viewed": LocalJSX.IvRecentlyViewed & JSXBase.HTMLAttributes<HTMLIvRecentlyViewedElement>;
            "iv-sidebar": LocalJSX.IvSidebar & JSXBase.HTMLAttributes<HTMLIvSidebarElement>;
            "iv-spinner": LocalJSX.IvSpinner & JSXBase.HTMLAttributes<HTMLIvSpinnerElement>;
            "iv-suggest": LocalJSX.IvSuggest & JSXBase.HTMLAttributes<HTMLIvSuggestElement>;
            "iv-tabs": LocalJSX.IvTabs & JSXBase.HTMLAttributes<HTMLIvTabsElement>;
            "iv-toast": LocalJSX.IvToast & JSXBase.HTMLAttributes<HTMLIvToastElement>;
            "iv-toast-container": LocalJSX.IvToastContainer & JSXBase.HTMLAttributes<HTMLIvToastContainerElement>;
            "iv-wishlist": LocalJSX.IvWishlist & JSXBase.HTMLAttributes<HTMLIvWishlistElement>;
            "iv-wishlist-view": LocalJSX.IvWishlistView & JSXBase.HTMLAttributes<HTMLIvWishlistViewElement>;
            "sw-in-grid-content": LocalJSX.SwInGridContent & JSXBase.HTMLAttributes<HTMLSwInGridContentElement>;
            "sw-size-guide": LocalJSX.SwSizeGuide & JSXBase.HTMLAttributes<HTMLSwSizeGuideElement>;
        }
    }
}
