/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NewsletterTimerOptions } from "./utils/shared/newsletter-timer";
import { NewsletterFailDetail, NewsletterSuccessDetail } from "./components/iv-newsletter/iv-newsletter";
export { NewsletterTimerOptions } from "./utils/shared/newsletter-timer";
export { NewsletterFailDetail, NewsletterSuccessDetail } from "./components/iv-newsletter/iv-newsletter";
export namespace Components {
    interface IvAccordion {
        /**
          * @default 'vertical'
         */
        "acordionlayout": 'vertical' | 'horizontal';
        "allowmultiple"?: boolean;
        /**
          * @default 'right'
         */
        "contentplacement": 'below' | 'right';
        "dropdownicon"?: 'chevron-down-outline' | 'add-outline';
        "labels": string;
        "startopen"?: boolean;
    }
    interface IvBanner {
        "bannerbuttontext"?: string;
        /**
          * @default 'div'
         */
        "bannertype": 'div' | 'section' | 'article';
        "bannerurl"?: string;
        "classmodifier"?: string;
    }
    interface IvButton {
        "buttonClick"?: (e?: MouseEvent) => void;
        "classmodifier"?: string;
        "eventdetail"?: string;
        "eventname"?: string;
        /**
          * @default 'button'
         */
        "type": string;
    }
    interface IvCard {
        "addtocarttext"?: string;
        "buttontext"?: string;
        /**
          * @default false
         */
        "calltoaction": boolean;
        "cardtype"?: string;
        "classmodifier"?: string;
        "data": Record<string, any>;
        "fields"?: string;
    }
    interface IvCarousel {
        /**
          * @default false
         */
        "autoplay": boolean;
        /**
          * @default 3000
         */
        "autoplayspeed": number;
        "halign"?: 'left' | 'center' | 'right';
        /**
          * @default false
         */
        "hasoverlay": boolean;
        "navarrows"?: boolean;
        "navdots"?: boolean;
        "showslidecount"?: boolean;
        "valign"?: 'top' | 'center' | 'bottom';
    }
    interface IvCompareProduct {
    }
    interface IvDynamicProducts {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction": boolean;
        /**
          * @default false
         */
        "carousel": boolean;
        /**
          * @default 'all'
         */
        "collectionhandle": string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring": string;
        "gridlayout"?: string;
        /**
          * @default 8
         */
        "limit": number;
        "requestedfields": string;
        /**
          * @default false
         */
        "reversed": boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED_AT'
         */
        "type": 'CREATED' | 'CREATED_AT' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvDynamicProductsCarousel {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction": boolean;
        /**
          * @default 'all'
         */
        "collectionhandle": string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring": string;
        "exclude"?: string;
        /**
          * @default 24
         */
        "limit": number;
        "requestedfields": string;
        /**
          * @default false
         */
        "reversed": boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED_AT'
         */
        "type": 'CREATED' | 'CREATED_AT' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvEventButton {
        /**
          * @default 'Click Me'
         */
        "buttontext": string;
        "eventdetail": any;
        "eventname": string;
    }
    interface IvFilters {
    }
    interface IvFooter {
        "footerbackground"?: string;
        "gridtemplateareas": string;
    }
    interface IvLayout {
        "classModifier"?: string;
        /**
          * @default '2rem'
         */
        "gap": string;
        "gridTemplateAreas"?: string;
        /**
          * @default 'center'
         */
        "horizontalAlign": string;
        "sectionId"?: string;
        /**
          * @default 'center'
         */
        "verticalAlign": string;
        /**
          * @default 'div'
         */
        "wrapperTag": string;
    }
    interface IvLink {
        "classmodifier"?: string;
        "linkariaLabel"?: string;
        "linkhref"?: string;
        /**
          * @default 'noopener noreferrer'
         */
        "linkrel": string;
        /**
          * @default '_self'
         */
        "linktarget": '_self' | '_blank' | '_parent' | '_top';
        /**
          * @default 'inline'
         */
        "linktype": 'inline' | 'wrapper' | 'nav' | 'button';
    }
    interface IvLinkList {
        /**
          * @default 'vertical'
         */
        "layout": 'vertical' | 'horizontal';
        "links": string;
        /**
          * @default 'social'
         */
        "linktype": 'social' | 'contact' | 'text';
        /**
          * @default false
         */
        "showicons": boolean;
    }
    interface IvModal {
        "newsletterpopuptimedelay"?: NewsletterTimerOptions['newsletterpopuptimedelay'];
        "newsletterpopuptrigger"?: NewsletterTimerOptions['newsletterpopuptrigger'];
    }
    interface IvNewsletter {
        "classmodifier"?: string;
        "formdescriptiontext"?: string;
        "formfailuremessage"?: string;
        "formimageheight"?: string;
        "formimageposition"?: 'top' | 'cover';
        "formimageurl"?: string;
        "formlabeltext"?: string;
        "formplaceholdertext"?: string;
        /**
          * @default false
         */
        "formstackbutton": boolean;
        /**
          * @default 'Subscribe'
         */
        "formsubmitbtntext": string;
        "formsuccessmessage"?: string;
        /**
          * @default 'h2'
         */
        "formtitletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        "formtitletext"?: string;
        /**
          * @default true
         */
        "includeloadingspinner": boolean;
        "newsletterpopupdisclaimer"?: string;
    }
    interface IvPill {
        /**
          * @default true
         */
        "bordered": boolean;
        "content": string;
        /**
          * @default 'none'
         */
        "externalspacing": 'none' | 'small' | 'medium' | 'large';
        /**
          * @default 'medium'
         */
        "internalspacing": 'small' | 'medium' | 'large';
        "label"?: string;
        /**
          * @default 'medium'
         */
        "roundedcorners": 'none' | 'small' | 'medium' | 'large';
    }
    interface IvPredictiveSearch {
        "action"?: string;
        "clearbutton"?: string;
        /**
          * @default false
         */
        "expandable": boolean;
        "gridlayout"?: string;
        /**
          * @default 'top'
         */
        "labelposition"?: 'inline' | 'top';
        /**
          * @default 3
         */
        "minchars": number;
        /**
          * @default 'No results found'
         */
        "noresultstext": string;
        "placeholder"?: string;
        "querybuttontext"?: string;
        /**
          * @default 'title'
         */
        "requestedfields": string;
        /**
          * @default 'product,article,page,collection'
         */
        "requestedresources": string;
        /**
          * @default 5
         */
        "resultslimit": number;
        "searchlabel"?: string;
        "showallbuttontext"?: string;
        "showspinner"?: boolean;
        "tablayout"?: string;
    }
    interface IvProductPin {
        "pinBehaviour": 'modal' | 'link' | 'tooltip';
        "pinCords": { x: number, y: number };
        "pinKey": number;
        "pinProduct": string;
    }
    interface IvProductUpsell {
    }
    interface IvRecentlyViewed {
        "componenttitle"?: string;
        "noviewhistory"?: string;
        /**
          * @default 4
         */
        "numbertoshow": number;
        /**
          * @default 'images,title,price'
         */
        "requestedfields"?: string;
        /**
          * @default 'span'
         */
        "titletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
    }
    interface IvShopTheLook {
        "behaviour": 'modal' | 'link' | 'tooltip';
        "coordinates": string;
        "producthandles"?: string;
    }
    interface IvSidebar {
        "newsletterpopuptimedelay"?: NewsletterTimerOptions['newsletterpopuptimedelay'];
        "newsletterpopuptrigger"?: NewsletterTimerOptions['newsletterpopuptrigger'];
    }
    interface IvSpinner {
        /**
          * @default false
         */
        "show": boolean;
    }
    interface IvSuggest {
        "banner"?: string;
        "bannerbuttontext"?: string;
        "bannertitle"?: string;
        /**
          * @default 'span'
         */
        "bannertitletag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        "bannerurl"?: string;
        "collections"?: string;
        "collectionstitle"?: string;
        "gridlayout"?: string;
        "products"?: string;
        "productstitle"?: string;
        "requestfields"?: string;
        "topqueries"?: string;
        "topquerytitle"?: string;
    }
    interface IvTabs {
        "classModifier"?: string;
        /**
          * @default []
         */
        "labels": string[];
        /**
          * @default 'horizontal'
         */
        "tabLayout": 'horizontal' | 'vertical';
    }
    interface IvToast {
        /**
          * @default 3000
         */
        "duration": number;
        "message": string;
        "toastId": number;
        /**
          * @default 'info'
         */
        "type": 'info' | 'success' | 'error' | 'warning';
    }
    interface IvToastContainer {
    }
    interface IvTwoColMedia {
        "gap": string;
        "horizontalalign": 'left' | 'center' | 'right';
        "mobilebehaviour": 'stack' | 'hide_specific' | 'hide_both';
        "stackorder"?: 'col-1' | 'col-2';
        "verticalalign": 'top' | 'middle' | 'bottom';
        "whichcolumn"?: 'col-1' | 'col-2';
    }
    interface IvWishlist {
        /**
          * @default 'Add to cart'
         */
        "buttonaddtocartvalue": string;
        /**
          * @default 'Add to wishlist'
         */
        "buttonaddvalue": string;
        /**
          * @default 'Remove from wishlist'
         */
        "buttonremovevalue": string;
        /**
          * @default 'modal'
         */
        "previewtype": 'modal' | 'pullout';
        /**
          * @default {}
         */
        "productdata": Record<string, any> | string;
        /**
          * @default 'id,title,price,image,url'
         */
        "usefields": string;
        /**
          * @default 'View wishlist'
         */
        "viewwishlistvalue": string;
        /**
          * @default 'Your wishlist is empty'
         */
        "wishlistempty": string;
    }
    interface IvWishlistView {
    }
    interface SwInGridContent {
    }
    interface SwSizeGuide {
    }
}
export interface IvButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvButtonElement;
}
export interface IvEventButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvEventButtonElement;
}
export interface IvNewsletterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvNewsletterElement;
}
export interface IvPredictiveSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvPredictiveSearchElement;
}
declare global {
    interface HTMLIvAccordionElement extends Components.IvAccordion, HTMLStencilElement {
    }
    var HTMLIvAccordionElement: {
        prototype: HTMLIvAccordionElement;
        new (): HTMLIvAccordionElement;
    };
    interface HTMLIvBannerElement extends Components.IvBanner, HTMLStencilElement {
    }
    var HTMLIvBannerElement: {
        prototype: HTMLIvBannerElement;
        new (): HTMLIvBannerElement;
    };
    interface HTMLIvButtonElementEventMap {
        "action": any;
    }
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvButtonElementEventMap>(type: K, listener: (this: HTMLIvButtonElement, ev: IvButtonCustomEvent<HTMLIvButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvButtonElementEventMap>(type: K, listener: (this: HTMLIvButtonElement, ev: IvButtonCustomEvent<HTMLIvButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLIvCardElement extends Components.IvCard, HTMLStencilElement {
    }
    var HTMLIvCardElement: {
        prototype: HTMLIvCardElement;
        new (): HTMLIvCardElement;
    };
    interface HTMLIvCarouselElement extends Components.IvCarousel, HTMLStencilElement {
    }
    var HTMLIvCarouselElement: {
        prototype: HTMLIvCarouselElement;
        new (): HTMLIvCarouselElement;
    };
    interface HTMLIvCompareProductElement extends Components.IvCompareProduct, HTMLStencilElement {
    }
    var HTMLIvCompareProductElement: {
        prototype: HTMLIvCompareProductElement;
        new (): HTMLIvCompareProductElement;
    };
    interface HTMLIvDynamicProductsElement extends Components.IvDynamicProducts, HTMLStencilElement {
    }
    var HTMLIvDynamicProductsElement: {
        prototype: HTMLIvDynamicProductsElement;
        new (): HTMLIvDynamicProductsElement;
    };
    interface HTMLIvDynamicProductsCarouselElement extends Components.IvDynamicProductsCarousel, HTMLStencilElement {
    }
    var HTMLIvDynamicProductsCarouselElement: {
        prototype: HTMLIvDynamicProductsCarouselElement;
        new (): HTMLIvDynamicProductsCarouselElement;
    };
    interface HTMLIvEventButtonElementEventMap {
        "action": any;
    }
    interface HTMLIvEventButtonElement extends Components.IvEventButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvEventButtonElementEventMap>(type: K, listener: (this: HTMLIvEventButtonElement, ev: IvEventButtonCustomEvent<HTMLIvEventButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvEventButtonElementEventMap>(type: K, listener: (this: HTMLIvEventButtonElement, ev: IvEventButtonCustomEvent<HTMLIvEventButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvEventButtonElement: {
        prototype: HTMLIvEventButtonElement;
        new (): HTMLIvEventButtonElement;
    };
    interface HTMLIvFiltersElement extends Components.IvFilters, HTMLStencilElement {
    }
    var HTMLIvFiltersElement: {
        prototype: HTMLIvFiltersElement;
        new (): HTMLIvFiltersElement;
    };
    interface HTMLIvFooterElement extends Components.IvFooter, HTMLStencilElement {
    }
    var HTMLIvFooterElement: {
        prototype: HTMLIvFooterElement;
        new (): HTMLIvFooterElement;
    };
    interface HTMLIvLayoutElement extends Components.IvLayout, HTMLStencilElement {
    }
    var HTMLIvLayoutElement: {
        prototype: HTMLIvLayoutElement;
        new (): HTMLIvLayoutElement;
    };
    interface HTMLIvLinkElement extends Components.IvLink, HTMLStencilElement {
    }
    var HTMLIvLinkElement: {
        prototype: HTMLIvLinkElement;
        new (): HTMLIvLinkElement;
    };
    interface HTMLIvLinkListElement extends Components.IvLinkList, HTMLStencilElement {
    }
    var HTMLIvLinkListElement: {
        prototype: HTMLIvLinkListElement;
        new (): HTMLIvLinkListElement;
    };
    interface HTMLIvModalElement extends Components.IvModal, HTMLStencilElement {
    }
    var HTMLIvModalElement: {
        prototype: HTMLIvModalElement;
        new (): HTMLIvModalElement;
    };
    interface HTMLIvNewsletterElementEventMap {
        "newsletterSuccess": NewsletterSuccessDetail;
        "newsletterFail": NewsletterFailDetail;
    }
    interface HTMLIvNewsletterElement extends Components.IvNewsletter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvNewsletterElementEventMap>(type: K, listener: (this: HTMLIvNewsletterElement, ev: IvNewsletterCustomEvent<HTMLIvNewsletterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvNewsletterElementEventMap>(type: K, listener: (this: HTMLIvNewsletterElement, ev: IvNewsletterCustomEvent<HTMLIvNewsletterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvNewsletterElement: {
        prototype: HTMLIvNewsletterElement;
        new (): HTMLIvNewsletterElement;
    };
    interface HTMLIvPillElement extends Components.IvPill, HTMLStencilElement {
    }
    var HTMLIvPillElement: {
        prototype: HTMLIvPillElement;
        new (): HTMLIvPillElement;
    };
    interface HTMLIvPredictiveSearchElementEventMap {
        "searchTermsChanged": any;
    }
    interface HTMLIvPredictiveSearchElement extends Components.IvPredictiveSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvPredictiveSearchElementEventMap>(type: K, listener: (this: HTMLIvPredictiveSearchElement, ev: IvPredictiveSearchCustomEvent<HTMLIvPredictiveSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvPredictiveSearchElementEventMap>(type: K, listener: (this: HTMLIvPredictiveSearchElement, ev: IvPredictiveSearchCustomEvent<HTMLIvPredictiveSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvPredictiveSearchElement: {
        prototype: HTMLIvPredictiveSearchElement;
        new (): HTMLIvPredictiveSearchElement;
    };
    interface HTMLIvProductPinElement extends Components.IvProductPin, HTMLStencilElement {
    }
    var HTMLIvProductPinElement: {
        prototype: HTMLIvProductPinElement;
        new (): HTMLIvProductPinElement;
    };
    interface HTMLIvProductUpsellElement extends Components.IvProductUpsell, HTMLStencilElement {
    }
    var HTMLIvProductUpsellElement: {
        prototype: HTMLIvProductUpsellElement;
        new (): HTMLIvProductUpsellElement;
    };
    interface HTMLIvRecentlyViewedElement extends Components.IvRecentlyViewed, HTMLStencilElement {
    }
    var HTMLIvRecentlyViewedElement: {
        prototype: HTMLIvRecentlyViewedElement;
        new (): HTMLIvRecentlyViewedElement;
    };
    interface HTMLIvShopTheLookElement extends Components.IvShopTheLook, HTMLStencilElement {
    }
    var HTMLIvShopTheLookElement: {
        prototype: HTMLIvShopTheLookElement;
        new (): HTMLIvShopTheLookElement;
    };
    interface HTMLIvSidebarElement extends Components.IvSidebar, HTMLStencilElement {
    }
    var HTMLIvSidebarElement: {
        prototype: HTMLIvSidebarElement;
        new (): HTMLIvSidebarElement;
    };
    interface HTMLIvSpinnerElement extends Components.IvSpinner, HTMLStencilElement {
    }
    var HTMLIvSpinnerElement: {
        prototype: HTMLIvSpinnerElement;
        new (): HTMLIvSpinnerElement;
    };
    interface HTMLIvSuggestElement extends Components.IvSuggest, HTMLStencilElement {
    }
    var HTMLIvSuggestElement: {
        prototype: HTMLIvSuggestElement;
        new (): HTMLIvSuggestElement;
    };
    interface HTMLIvTabsElement extends Components.IvTabs, HTMLStencilElement {
    }
    var HTMLIvTabsElement: {
        prototype: HTMLIvTabsElement;
        new (): HTMLIvTabsElement;
    };
    interface HTMLIvToastElement extends Components.IvToast, HTMLStencilElement {
    }
    var HTMLIvToastElement: {
        prototype: HTMLIvToastElement;
        new (): HTMLIvToastElement;
    };
    interface HTMLIvToastContainerElement extends Components.IvToastContainer, HTMLStencilElement {
    }
    var HTMLIvToastContainerElement: {
        prototype: HTMLIvToastContainerElement;
        new (): HTMLIvToastContainerElement;
    };
    interface HTMLIvTwoColMediaElement extends Components.IvTwoColMedia, HTMLStencilElement {
    }
    var HTMLIvTwoColMediaElement: {
        prototype: HTMLIvTwoColMediaElement;
        new (): HTMLIvTwoColMediaElement;
    };
    interface HTMLIvWishlistElement extends Components.IvWishlist, HTMLStencilElement {
    }
    var HTMLIvWishlistElement: {
        prototype: HTMLIvWishlistElement;
        new (): HTMLIvWishlistElement;
    };
    interface HTMLIvWishlistViewElement extends Components.IvWishlistView, HTMLStencilElement {
    }
    var HTMLIvWishlistViewElement: {
        prototype: HTMLIvWishlistViewElement;
        new (): HTMLIvWishlistViewElement;
    };
    interface HTMLSwInGridContentElement extends Components.SwInGridContent, HTMLStencilElement {
    }
    var HTMLSwInGridContentElement: {
        prototype: HTMLSwInGridContentElement;
        new (): HTMLSwInGridContentElement;
    };
    interface HTMLSwSizeGuideElement extends Components.SwSizeGuide, HTMLStencilElement {
    }
    var HTMLSwSizeGuideElement: {
        prototype: HTMLSwSizeGuideElement;
        new (): HTMLSwSizeGuideElement;
    };
    interface HTMLElementTagNameMap {
        "iv-accordion": HTMLIvAccordionElement;
        "iv-banner": HTMLIvBannerElement;
        "iv-button": HTMLIvButtonElement;
        "iv-card": HTMLIvCardElement;
        "iv-carousel": HTMLIvCarouselElement;
        "iv-compare-product": HTMLIvCompareProductElement;
        "iv-dynamic-products": HTMLIvDynamicProductsElement;
        "iv-dynamic-products-carousel": HTMLIvDynamicProductsCarouselElement;
        "iv-event-button": HTMLIvEventButtonElement;
        "iv-filters": HTMLIvFiltersElement;
        "iv-footer": HTMLIvFooterElement;
        "iv-layout": HTMLIvLayoutElement;
        "iv-link": HTMLIvLinkElement;
        "iv-link-list": HTMLIvLinkListElement;
        "iv-modal": HTMLIvModalElement;
        "iv-newsletter": HTMLIvNewsletterElement;
        "iv-pill": HTMLIvPillElement;
        "iv-predictive-search": HTMLIvPredictiveSearchElement;
        "iv-product-pin": HTMLIvProductPinElement;
        "iv-product-upsell": HTMLIvProductUpsellElement;
        "iv-recently-viewed": HTMLIvRecentlyViewedElement;
        "iv-shop-the-look": HTMLIvShopTheLookElement;
        "iv-sidebar": HTMLIvSidebarElement;
        "iv-spinner": HTMLIvSpinnerElement;
        "iv-suggest": HTMLIvSuggestElement;
        "iv-tabs": HTMLIvTabsElement;
        "iv-toast": HTMLIvToastElement;
        "iv-toast-container": HTMLIvToastContainerElement;
        "iv-two-col-media": HTMLIvTwoColMediaElement;
        "iv-wishlist": HTMLIvWishlistElement;
        "iv-wishlist-view": HTMLIvWishlistViewElement;
        "sw-in-grid-content": HTMLSwInGridContentElement;
        "sw-size-guide": HTMLSwSizeGuideElement;
    }
}
declare namespace LocalJSX {
    interface IvAccordion {
        /**
          * @default 'vertical'
         */
        "acordionlayout"?: 'vertical' | 'horizontal';
        "allowmultiple"?: boolean;
        /**
          * @default 'right'
         */
        "contentplacement"?: 'below' | 'right';
        "dropdownicon"?: 'chevron-down-outline' | 'add-outline';
        "labels"?: string;
        "startopen"?: boolean;
    }
    interface IvBanner {
        "bannerbuttontext"?: string;
        /**
          * @default 'div'
         */
        "bannertype"?: 'div' | 'section' | 'article';
        "bannerurl"?: string;
        "classmodifier"?: string;
    }
    interface IvButton {
        "buttonClick"?: (e?: MouseEvent) => void;
        "classmodifier"?: string;
        "eventdetail"?: string;
        "eventname"?: string;
        "onAction"?: (event: IvButtonCustomEvent<any>) => void;
        /**
          * @default 'button'
         */
        "type"?: string;
    }
    interface IvCard {
        "addtocarttext"?: string;
        "buttontext"?: string;
        /**
          * @default false
         */
        "calltoaction"?: boolean;
        "cardtype"?: string;
        "classmodifier"?: string;
        "data"?: Record<string, any>;
        "fields"?: string;
    }
    interface IvCarousel {
        /**
          * @default false
         */
        "autoplay"?: boolean;
        /**
          * @default 3000
         */
        "autoplayspeed"?: number;
        "halign"?: 'left' | 'center' | 'right';
        /**
          * @default false
         */
        "hasoverlay"?: boolean;
        "navarrows"?: boolean;
        "navdots"?: boolean;
        "showslidecount"?: boolean;
        "valign"?: 'top' | 'center' | 'bottom';
    }
    interface IvCompareProduct {
    }
    interface IvDynamicProducts {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction"?: boolean;
        /**
          * @default false
         */
        "carousel"?: boolean;
        /**
          * @default 'all'
         */
        "collectionhandle"?: string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring"?: string;
        "gridlayout"?: string;
        /**
          * @default 8
         */
        "limit"?: number;
        "requestedfields"?: string;
        /**
          * @default false
         */
        "reversed"?: boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED_AT'
         */
        "type"?: 'CREATED' | 'CREATED_AT' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvDynamicProductsCarousel {
        "addtocarttext"?: string;
        "buttontext"?: string;
        "cachettl"?: number;
        /**
          * @default false
         */
        "calltoaction"?: boolean;
        /**
          * @default 'all'
         */
        "collectionhandle"?: string;
        "componenttitle"?: string;
        /**
          * @default 'No products found'
         */
        "emptystring"?: string;
        "exclude"?: string;
        /**
          * @default 24
         */
        "limit"?: number;
        "requestedfields"?: string;
        /**
          * @default false
         */
        "reversed"?: boolean;
        /**
          * @default true
         */
        "stale"?: boolean;
        /**
          * @default 'h2'
         */
        "titletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        /**
          * @default 'CREATED_AT'
         */
        "type"?: 'CREATED' | 'CREATED_AT' | 'BEST_SELLING' | 'PRICE' | 'TITLE' | 'RELEVANCE';
    }
    interface IvEventButton {
        /**
          * @default 'Click Me'
         */
        "buttontext"?: string;
        "eventdetail"?: any;
        "eventname"?: string;
        "onAction"?: (event: IvEventButtonCustomEvent<any>) => void;
    }
    interface IvFilters {
    }
    interface IvFooter {
        "footerbackground"?: string;
        "gridtemplateareas"?: string;
    }
    interface IvLayout {
        "classModifier"?: string;
        /**
          * @default '2rem'
         */
        "gap"?: string;
        "gridTemplateAreas"?: string;
        /**
          * @default 'center'
         */
        "horizontalAlign"?: string;
        "sectionId"?: string;
        /**
          * @default 'center'
         */
        "verticalAlign"?: string;
        /**
          * @default 'div'
         */
        "wrapperTag"?: string;
    }
    interface IvLink {
        "classmodifier"?: string;
        "linkariaLabel"?: string;
        "linkhref"?: string;
        /**
          * @default 'noopener noreferrer'
         */
        "linkrel"?: string;
        /**
          * @default '_self'
         */
        "linktarget"?: '_self' | '_blank' | '_parent' | '_top';
        /**
          * @default 'inline'
         */
        "linktype"?: 'inline' | 'wrapper' | 'nav' | 'button';
    }
    interface IvLinkList {
        /**
          * @default 'vertical'
         */
        "layout"?: 'vertical' | 'horizontal';
        "links"?: string;
        /**
          * @default 'social'
         */
        "linktype"?: 'social' | 'contact' | 'text';
        /**
          * @default false
         */
        "showicons"?: boolean;
    }
    interface IvModal {
        "newsletterpopuptimedelay"?: NewsletterTimerOptions['newsletterpopuptimedelay'];
        "newsletterpopuptrigger"?: NewsletterTimerOptions['newsletterpopuptrigger'];
    }
    interface IvNewsletter {
        "classmodifier"?: string;
        "formdescriptiontext"?: string;
        "formfailuremessage"?: string;
        "formimageheight"?: string;
        "formimageposition"?: 'top' | 'cover';
        "formimageurl"?: string;
        "formlabeltext"?: string;
        "formplaceholdertext"?: string;
        /**
          * @default false
         */
        "formstackbutton"?: boolean;
        /**
          * @default 'Subscribe'
         */
        "formsubmitbtntext"?: string;
        "formsuccessmessage"?: string;
        /**
          * @default 'h2'
         */
        "formtitletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        "formtitletext"?: string;
        /**
          * @default true
         */
        "includeloadingspinner"?: boolean;
        "newsletterpopupdisclaimer"?: string;
        "onNewsletterFail"?: (event: IvNewsletterCustomEvent<NewsletterFailDetail>) => void;
        "onNewsletterSuccess"?: (event: IvNewsletterCustomEvent<NewsletterSuccessDetail>) => void;
    }
    interface IvPill {
        /**
          * @default true
         */
        "bordered"?: boolean;
        "content"?: string;
        /**
          * @default 'none'
         */
        "externalspacing"?: 'none' | 'small' | 'medium' | 'large';
        /**
          * @default 'medium'
         */
        "internalspacing"?: 'small' | 'medium' | 'large';
        "label"?: string;
        /**
          * @default 'medium'
         */
        "roundedcorners"?: 'none' | 'small' | 'medium' | 'large';
    }
    interface IvPredictiveSearch {
        "action"?: string;
        "clearbutton"?: string;
        /**
          * @default false
         */
        "expandable"?: boolean;
        "gridlayout"?: string;
        /**
          * @default 'top'
         */
        "labelposition"?: 'inline' | 'top';
        /**
          * @default 3
         */
        "minchars"?: number;
        /**
          * @default 'No results found'
         */
        "noresultstext"?: string;
        "onSearchTermsChanged"?: (event: IvPredictiveSearchCustomEvent<any>) => void;
        "placeholder"?: string;
        "querybuttontext"?: string;
        /**
          * @default 'title'
         */
        "requestedfields"?: string;
        /**
          * @default 'product,article,page,collection'
         */
        "requestedresources"?: string;
        /**
          * @default 5
         */
        "resultslimit"?: number;
        "searchlabel"?: string;
        "showallbuttontext"?: string;
        "showspinner"?: boolean;
        "tablayout"?: string;
    }
    interface IvProductPin {
        "pinBehaviour"?: 'modal' | 'link' | 'tooltip';
        "pinCords"?: { x: number, y: number };
        "pinKey"?: number;
        "pinProduct"?: string;
    }
    interface IvProductUpsell {
    }
    interface IvRecentlyViewed {
        "componenttitle"?: string;
        "noviewhistory"?: string;
        /**
          * @default 4
         */
        "numbertoshow"?: number;
        /**
          * @default 'images,title,price'
         */
        "requestedfields"?: string;
        /**
          * @default 'span'
         */
        "titletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
    }
    interface IvShopTheLook {
        "behaviour"?: 'modal' | 'link' | 'tooltip';
        "coordinates"?: string;
        "producthandles"?: string;
    }
    interface IvSidebar {
        "newsletterpopuptimedelay"?: NewsletterTimerOptions['newsletterpopuptimedelay'];
        "newsletterpopuptrigger"?: NewsletterTimerOptions['newsletterpopuptrigger'];
    }
    interface IvSpinner {
        /**
          * @default false
         */
        "show"?: boolean;
    }
    interface IvSuggest {
        "banner"?: string;
        "bannerbuttontext"?: string;
        "bannertitle"?: string;
        /**
          * @default 'span'
         */
        "bannertitletag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
        "bannerurl"?: string;
        "collections"?: string;
        "collectionstitle"?: string;
        "gridlayout"?: string;
        "products"?: string;
        "productstitle"?: string;
        "requestfields"?: string;
        "topqueries"?: string;
        "topquerytitle"?: string;
    }
    interface IvTabs {
        "classModifier"?: string;
        /**
          * @default []
         */
        "labels"?: string[];
        /**
          * @default 'horizontal'
         */
        "tabLayout"?: 'horizontal' | 'vertical';
    }
    interface IvToast {
        /**
          * @default 3000
         */
        "duration"?: number;
        "message"?: string;
        "toastId"?: number;
        /**
          * @default 'info'
         */
        "type"?: 'info' | 'success' | 'error' | 'warning';
    }
    interface IvToastContainer {
    }
    interface IvTwoColMedia {
        "gap"?: string;
        "horizontalalign"?: 'left' | 'center' | 'right';
        "mobilebehaviour"?: 'stack' | 'hide_specific' | 'hide_both';
        "stackorder"?: 'col-1' | 'col-2';
        "verticalalign"?: 'top' | 'middle' | 'bottom';
        "whichcolumn"?: 'col-1' | 'col-2';
    }
    interface IvWishlist {
        /**
          * @default 'Add to cart'
         */
        "buttonaddtocartvalue"?: string;
        /**
          * @default 'Add to wishlist'
         */
        "buttonaddvalue"?: string;
        /**
          * @default 'Remove from wishlist'
         */
        "buttonremovevalue"?: string;
        /**
          * @default 'modal'
         */
        "previewtype"?: 'modal' | 'pullout';
        /**
          * @default {}
         */
        "productdata"?: Record<string, any> | string;
        /**
          * @default 'id,title,price,image,url'
         */
        "usefields"?: string;
        /**
          * @default 'View wishlist'
         */
        "viewwishlistvalue"?: string;
        /**
          * @default 'Your wishlist is empty'
         */
        "wishlistempty"?: string;
    }
    interface IvWishlistView {
    }
    interface SwInGridContent {
    }
    interface SwSizeGuide {
    }
    interface IntrinsicElements {
        "iv-accordion": IvAccordion;
        "iv-banner": IvBanner;
        "iv-button": IvButton;
        "iv-card": IvCard;
        "iv-carousel": IvCarousel;
        "iv-compare-product": IvCompareProduct;
        "iv-dynamic-products": IvDynamicProducts;
        "iv-dynamic-products-carousel": IvDynamicProductsCarousel;
        "iv-event-button": IvEventButton;
        "iv-filters": IvFilters;
        "iv-footer": IvFooter;
        "iv-layout": IvLayout;
        "iv-link": IvLink;
        "iv-link-list": IvLinkList;
        "iv-modal": IvModal;
        "iv-newsletter": IvNewsletter;
        "iv-pill": IvPill;
        "iv-predictive-search": IvPredictiveSearch;
        "iv-product-pin": IvProductPin;
        "iv-product-upsell": IvProductUpsell;
        "iv-recently-viewed": IvRecentlyViewed;
        "iv-shop-the-look": IvShopTheLook;
        "iv-sidebar": IvSidebar;
        "iv-spinner": IvSpinner;
        "iv-suggest": IvSuggest;
        "iv-tabs": IvTabs;
        "iv-toast": IvToast;
        "iv-toast-container": IvToastContainer;
        "iv-two-col-media": IvTwoColMedia;
        "iv-wishlist": IvWishlist;
        "iv-wishlist-view": IvWishlistView;
        "sw-in-grid-content": SwInGridContent;
        "sw-size-guide": SwSizeGuide;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-accordion": LocalJSX.IvAccordion & JSXBase.HTMLAttributes<HTMLIvAccordionElement>;
            "iv-banner": LocalJSX.IvBanner & JSXBase.HTMLAttributes<HTMLIvBannerElement>;
            "iv-button": LocalJSX.IvButton & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
            "iv-card": LocalJSX.IvCard & JSXBase.HTMLAttributes<HTMLIvCardElement>;
            "iv-carousel": LocalJSX.IvCarousel & JSXBase.HTMLAttributes<HTMLIvCarouselElement>;
            "iv-compare-product": LocalJSX.IvCompareProduct & JSXBase.HTMLAttributes<HTMLIvCompareProductElement>;
            "iv-dynamic-products": LocalJSX.IvDynamicProducts & JSXBase.HTMLAttributes<HTMLIvDynamicProductsElement>;
            "iv-dynamic-products-carousel": LocalJSX.IvDynamicProductsCarousel & JSXBase.HTMLAttributes<HTMLIvDynamicProductsCarouselElement>;
            "iv-event-button": LocalJSX.IvEventButton & JSXBase.HTMLAttributes<HTMLIvEventButtonElement>;
            "iv-filters": LocalJSX.IvFilters & JSXBase.HTMLAttributes<HTMLIvFiltersElement>;
            "iv-footer": LocalJSX.IvFooter & JSXBase.HTMLAttributes<HTMLIvFooterElement>;
            "iv-layout": LocalJSX.IvLayout & JSXBase.HTMLAttributes<HTMLIvLayoutElement>;
            "iv-link": LocalJSX.IvLink & JSXBase.HTMLAttributes<HTMLIvLinkElement>;
            "iv-link-list": LocalJSX.IvLinkList & JSXBase.HTMLAttributes<HTMLIvLinkListElement>;
            "iv-modal": LocalJSX.IvModal & JSXBase.HTMLAttributes<HTMLIvModalElement>;
            "iv-newsletter": LocalJSX.IvNewsletter & JSXBase.HTMLAttributes<HTMLIvNewsletterElement>;
            "iv-pill": LocalJSX.IvPill & JSXBase.HTMLAttributes<HTMLIvPillElement>;
            "iv-predictive-search": LocalJSX.IvPredictiveSearch & JSXBase.HTMLAttributes<HTMLIvPredictiveSearchElement>;
            "iv-product-pin": LocalJSX.IvProductPin & JSXBase.HTMLAttributes<HTMLIvProductPinElement>;
            "iv-product-upsell": LocalJSX.IvProductUpsell & JSXBase.HTMLAttributes<HTMLIvProductUpsellElement>;
            "iv-recently-viewed": LocalJSX.IvRecentlyViewed & JSXBase.HTMLAttributes<HTMLIvRecentlyViewedElement>;
            "iv-shop-the-look": LocalJSX.IvShopTheLook & JSXBase.HTMLAttributes<HTMLIvShopTheLookElement>;
            "iv-sidebar": LocalJSX.IvSidebar & JSXBase.HTMLAttributes<HTMLIvSidebarElement>;
            "iv-spinner": LocalJSX.IvSpinner & JSXBase.HTMLAttributes<HTMLIvSpinnerElement>;
            "iv-suggest": LocalJSX.IvSuggest & JSXBase.HTMLAttributes<HTMLIvSuggestElement>;
            "iv-tabs": LocalJSX.IvTabs & JSXBase.HTMLAttributes<HTMLIvTabsElement>;
            "iv-toast": LocalJSX.IvToast & JSXBase.HTMLAttributes<HTMLIvToastElement>;
            "iv-toast-container": LocalJSX.IvToastContainer & JSXBase.HTMLAttributes<HTMLIvToastContainerElement>;
            "iv-two-col-media": LocalJSX.IvTwoColMedia & JSXBase.HTMLAttributes<HTMLIvTwoColMediaElement>;
            "iv-wishlist": LocalJSX.IvWishlist & JSXBase.HTMLAttributes<HTMLIvWishlistElement>;
            "iv-wishlist-view": LocalJSX.IvWishlistView & JSXBase.HTMLAttributes<HTMLIvWishlistViewElement>;
            "sw-in-grid-content": LocalJSX.SwInGridContent & JSXBase.HTMLAttributes<HTMLSwInGridContentElement>;
            "sw-size-guide": LocalJSX.SwSizeGuide & JSXBase.HTMLAttributes<HTMLSwSizeGuideElement>;
        }
    }
}
